/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://rskvmpocyrh4dpisfj7cwtqona.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-rn64rdbshvhxxor3pt2qo7h23q",
    "aws_cognito_identity_pool_id": "us-west-2:e47d55a6-7a3b-4aac-9d25-3bce5536db3c",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_6THq6EH4u",
    "aws_user_pools_web_client_id": "58btiiu4ktn91oq023lg1b4u5g",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "notairdropfc8203a2c29b4546a28228ca013e2a5953520-staging",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
